#pragma once

#include <string>


const std::string certificate = //{
                "-----BEGIN CERTIFICATE-----\n"
                "MIIDfTCCAmUCFDHbl8DpsaE9xtJ2Xn8mpu+g3QQ0MA0GCSqGSIb3DQEBCwUAMHsx\n"
                "CzAJBgNVBAYTAkNOMQ8wDQYDVQQIDAZGdUppYW4xDzANBgNVBAcMBkZ1WmhvdTEL\n"
                "MAkGA1UECgwCR00xCzAJBgNVBAsMAkdNMQswCQYDVQQDDAJHTTEjMCEGCSqGSIb3\n"
                "DQEJARYUZmFrZWFkZHJlc3NAZmFrZS5jb20wHhcNMjAwNzIwMDY0MTA5WhcNMzAw\n"
                "NzE4MDY0MTA5WjB7MQswCQYDVQQGEwJDTjEPMA0GA1UECAwGRnVKaWFuMQ8wDQYD\n"
                "VQQHDAZGdVpob3UxCzAJBgNVBAoMAkdNMQswCQYDVQQLDAJHTTELMAkGA1UEAwwC\n"
                "R00xIzAhBgkqhkiG9w0BCQEWFGZha2VhZGRyZXNzQGZha2UuY29tMIIBIjANBgkq\n"
                "hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuqSF08BCMv7pBYz+JObgJMRJ1Cf0xlNm\n"
                "Ag6L9NZ4Cu1Uy1TRrA6mOD/IFbuwXddMXLSvO2O8VlHfhXG/XKZPOaW5CI3sDfAQ\n"
                "SWhzyPeFkfuzsBpavV0ECO+8QmQ2d0mskC15lS0emeCAgwUC5XL1U5T9IgTlh5q+\n"
                "0WiYpPhiaZVXh/fk4+HQk2NCzaH8K5sme088y5rqmpYmYQtDakXMcXvgdFB7tGTy\n"
                "LlFX0Uy5EJkzyTAU96OoOtwhSyTdCSPxU3R30JmNm+vpvQjwYx/apQ1C+k596MoZ\n"
                "wMswuxTfBC6x6TtQyqzuJ6W1uIUDaCIURev90AmezMEi9+jYMae7ZQIDAQABMA0G\n"
                "CSqGSIb3DQEBCwUAA4IBAQBCTzDrfLNtlbOcSpQcb/t1v9wXN1rM9h61xaFVv/gd\n"
                "kqZhKvuJN+qZ46SoZ8PjcSOTmQz8WAPZ9XG//ripPk4STDih++P4AKWPuZduK9lf\n"
                "Bqd6liMfqXJCAGg3fDkvjQv9Jqj4TX7qDQmyR7Sa2VFv7ZHnPUqTizwORvd4zq/f\n"
                "yHpMI5qHV6M7g609s7b++xKhAp7IlPpVGyr1h+EkUM6fP74Yi1nKB7HwoeX7NFil\n"
                "CoBI+EO5pcWbhcj6Gj4caUbVYONYxUOGV84FxFnnze0wDLlxaxSy3NvqHCPtC2h9\n"
                "dpXpgL8achlcCEouYxeA+JLhP8yjmpefBzhcjh09qMWM\n"
                "-----END CERTIFICATE-----"; //}
const std::string privateKey  = //{
                "-----BEGIN RSA PRIVATE KEY-----\n"
                "MIIEpAIBAAKCAQEAuqSF08BCMv7pBYz+JObgJMRJ1Cf0xlNmAg6L9NZ4Cu1Uy1TR\n"
                "rA6mOD/IFbuwXddMXLSvO2O8VlHfhXG/XKZPOaW5CI3sDfAQSWhzyPeFkfuzsBpa\n"
                "vV0ECO+8QmQ2d0mskC15lS0emeCAgwUC5XL1U5T9IgTlh5q+0WiYpPhiaZVXh/fk\n"
                "4+HQk2NCzaH8K5sme088y5rqmpYmYQtDakXMcXvgdFB7tGTyLlFX0Uy5EJkzyTAU\n"
                "96OoOtwhSyTdCSPxU3R30JmNm+vpvQjwYx/apQ1C+k596MoZwMswuxTfBC6x6TtQ\n"
                "yqzuJ6W1uIUDaCIURev90AmezMEi9+jYMae7ZQIDAQABAoIBAErG+bsxzxQBXzjT\n"
                "GUuNmIYCgpXWgFIpPbhbPaWVe7jdB1kDnZGyuNPWcgKLFQkz5itKVN6VgfKPkN81\n"
                "CHdFRn6RMAYGXmnjIZNXnvQIf2JSltZaaLpvlttBuYpb/hpi0RlertSepCEAelyD\n"
                "2Ho3SaT4D0be8VsYG5Vos6d8wGkONSVT2rFq1wTgvd5fO+WTObamQ4p/mjMozmnh\n"
                "KEEbHNhewErTnv7VqQWTkg0ZLYEfUk11T7+kkp2snhe0J5I4REa5CemVPbc6Y1q4\n"
                "wYgxEHEUOxJcfZbl1o2fLrktLqPmchy07r0Smz9nhCFBOOgZnRdHpGrTMxLq7fM0\n"
                "+MNGuIECgYEA9JmiK+yCzUGww0OeF5H5XVfZ5aVGhje3r7XTrzfTf2ZgcBX9CKCX\n"
                "rvaHOsmjBHQdrcPPIKPJ//Ha9rqjltBhYbfvdtbf5NsJfHdT9S0BQJQMHNHQGdCg\n"
                "zbgD6PCmUFTpiV3ZeMO0JPLZCiZLyuUUAQbQgYyEU6lzTbjkdES4tMUCgYEAw1dj\n"
                "hKzyJIUXN0XLhGGjRkwz8mDYsJpB593pEAbGDVLok98clthIYls+YhdCpPq8P4hA\n"
                "+R14+dvzc1prqAcinGi4WYbVEpotRS4chYC4E6KSaNnEvHPujNiqdOtCouol8v9H\n"
                "BJLtMzmqvFpQmWHzDANh/6+twY6/IHHka80JliECgYAElUxgnlHlHrH9NqsjreyK\n"
                "PzcqAmrL4QdkF3gb9GPWI0jzULYpDzlIYf4ur9CKKNLVirG63tbOIO4FaYHfNZBd\n"
                "kGDATU5sr14CIwpDsdAwMZX4hEXt9ebNdAE+wCOdpbmqhUOp66DYgGRouEb7SkeR\n"
                "rVsC0ms4Vhh/AFPnidIcMQKBgQC2ExhhrEovHBadoGKoS9HCTnkE7JxNUBsqIj+A\n"
                "fq/P7311hzrAp2wgsWeeSowF9ufMWBYnnP8L9aYf2SILhksOetWKLREhu6+Ckg5n\n"
                "qajqNFg/fuvPtEef5LxNKpP8Aj/JFYR+kOyjGJc55PzHWvMOOYD4sClHBuTDOyVs\n"
                "DbtnwQKBgQCklhximnO4cYZG1+wKD0LbwEcZ1ZsvZa/Lb85GkkA7bterKEp+x3fd\n"
                "aw6V1smBAPfWAkFfkVla4izWtUZxSq8OPnvPN8mkuklEdEuFrFHGwCako6L23RxM\n"
                "tWeZqgxWwSczlrS0HcDJNEjSfDIGckYBVQdMTUFHwBES44WJWWLD8Q==\n"
                "-----END RSA PRIVATE KEY-----"; //}

